[tool.poetry]
name = "mcnugget"
version = "0.1.0"
description = "The McNugget of Data Analysis"
authors = ["emiliano bonilla <ebonilla@synnaxlabs.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
synnax = { path = "../../synnax/client/py", develop = true }
toml = "^0.10.2"
matplotlib = "^3.7.1"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"

[tool.synnax]
host = "10.0.0.15"
port = 9090
username = "synnax"
password = "seldon"
secure = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
